name: asfiyahi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  retrofit: ^1.2.0
  json_serializable: ^4.0.2
  json_annotation: ^4.0.1
  logger: any
  date_format: ^2.0.2
  flutter_vector_icons: ^1.0.0
  font_awesome_flutter: ^9.0.0
  webview_flutter: 2.0.4
  webfeed: ^0.4.2
  cached_network_image: 2.0.0
  video_player: 2.1.1
  #chewie: ^0.12.0
  better_player: ^0.0.64
  simple_animations: ^1.3.6
  shimmer: ^1.0.1
  youtube_player_flutter: ^8.0.0
  youtube_api:
    path: youtube_api-0.8.0/
  jiffy: ^4.1.0
  youtube_api_v3: ^0.0.3
  #wc_flutter_share: ^0.2.2
  wakelock: 0.5.2
  assets_audio_player: ^2.0.15
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.7
  timeline_tile: ^2.0.0
  volume: ^1.0.1
  wc_flutter_share: ^0.4.0
  salomon_bottom_bar: ^3.1.0
  google_mobile_ads: ^0.13.4


dev_dependencies:
  retrofit_generator: ^1.2.0
  build_runner: ^1.7.4
    #flutter pub run build_runner build
  flutter_launcher_icons: ^0.8.1
    #flutter pub run flutter_launcher_icons:main
  flutter_test:
    sdk: flutter

dependency_overrides:
  path_provider: ^1.6.27



flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: assets/images/launcher.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CeraPro
      fonts:
        - asset: fonts/cerapro_regular.ttf
        - asset: fonts/cerapro_bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
